// Author: Kevin Pabón

// internal imports
import type { UserInterface } from '@/interfaces/UserInterface'

/**
 * Data required to create a User; id and timestamps are generated by the
 * database. `password` is added here on purpose: the API never returns it,
 * so it is not part of UserInterface, but it does travel on the way in.
 */
export type CreateUserDTO = Omit<UserInterface, 'id' | 'createdAt' | 'updatedAt'> & {
  password: string
}
