// Author: Kevin Pabón

// internal imports
import type { BrandInterface } from '@/interfaces/BrandInterface'

/** Data required to create a Brand; id and timestamps are generated by the service. */
export type CreateBrandDTO = Omit<BrandInterface, 'id' | 'createdAt' | 'updatedAt'>
