// Author: Kevin Pabón

// internal imports
import type { CreatorInterface } from '@/interfaces/CreatorInterface'

/** Data required to create a Creator; id and timestamps are generated by the service. */
export type CreateCreatorDTO = Omit<CreatorInterface, 'id' | 'createdAt' | 'updatedAt'>
