// Author: Kevin Pabón

// internal imports
import type { OrderInterface } from '@/interfaces/OrderInterface'

/** Data required to create an Order; id and timestamps are generated by the service. */
export type CreateOrderDTO = Omit<OrderInterface, 'id' | 'createdAt' | 'updatedAt'>
