// Author: Kevin Pabón

// internal imports
import type { UserInterface } from '@/interfaces/UserInterface'

/** Data required to create a User; id and timestamps are generated by the service. */
export type CreateUserDTO = Omit<UserInterface, 'id' | 'createdAt' | 'updatedAt'>
